# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: trusty
      language: r
r:
  - oldrel
  - release
  - devel
    - os: osx
    language: r
r:
  - oldrel
  - release
  - devel
    - os: osx
    language: r
r:
  - oldrel
  - release
  - devel
      osx_image: xcode9
    - os: osx
    language: r
r:
  - oldrel
  - release
  - devel
      osx_image: xcode9.4
