# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: osx
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.4      
    - os: windows

