## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: r

r:
  - oldrel
  - release
  - devel

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libnlopt-dev ghostscript
  
services:
 - xvfb


notifications:
  email:
    on_success: change
    on_failure: change
  