# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

cache: packages
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: linux
      dist: trusty
      sudo: true
    - os: osx
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.4

r:
  - oldrel
  - release
  - devel
